### ISSUE TITLE
Repo verwijderen, verplaatsen of open zetten

### ISSUE THREAD

**Issue by timvdalen** [timvdalen/2II36-project#1]
Hi guys,

Ik moet de repo verwijderen, public maken of ownership transferren.
Iemand een voorkeur?

Als ik binnen een paar uur geen reactie heb verwijder ik hem wel.

**Comment by ThomHurks** [comment]
Public? Voor het nageslacht 😜

**Comment by timvdalen** [comment]
Ik vind het prima, iemand bezwaar?

**Comment by Barttje** [comment]
maak maar public :D

---

Van: Tim van Dalen [notifications@github.com]
Verzonden: dinsdag 24 maart 2015 21:07
Aan: timvdalen/2II36-project
Onderwerp: Re: [2II36-project] Repo verwijderen, verplaatsen of open zetten (#1)

Ik vind het prima, iemand bezwaar?

�

**Comment by vdevos** [comment]
Lees het nu pas, lekker open gooien inderdaad!
